server:
  port: 8083
Logger:
  level: "debug"
database:
  mongodb: "mongodb://127.0.0.1:27017"
  db: "liteblog"
Auth:
  accesstokenexpiration: 24
  refereshtokenexpiration: 30
  jwtsecret: "123456"
  passwordsalt: "123456"
